// Export pages
export '/pages/parking/start_screen/start_screen_widget.dart'
    show StartScreenWidget;
export '/pages/parking/phone_auth_page/phone_auth_page_widget.dart'
    show PhoneAuthPageWidget;
export '/pages/parking/o_t_pverification_new_p/o_t_pverification_new_p_widget.dart'
    show OTPverificationNewPWidget;
export '/pages/parking/business_profile_adminfinal/business_profile_adminfinal_widget.dart'
    show BusinessProfileAdminfinalWidget;
export '/pages/parking/outletlist_page/outletlist_page_widget.dart'
    show OutletlistPageWidget;
export '/pages/parking/add_outlet_page/add_outlet_page_widget.dart'
    show AddOutletPageWidget;
export '/pages/parking/create_user_profile_new_p/create_user_profile_new_p_widget.dart'
    show CreateUserProfileNewPWidget;
export '/pages/parking/add_business_profile/add_business_profile_widget.dart'
    show AddBusinessProfileWidget;
export '/pages/parking/edit_busines_profile/edit_busines_profile_widget.dart'
    show EditBusinesProfileWidget;
export '/pages/parking/account/account_widget.dart' show AccountWidget;
export '/pages/parking/edit_userprofile/edit_userprofile_widget.dart'
    show EditUserprofileWidget;
export '/pages/parking/masters_new/masters_new_widget.dart'
    show MastersNewWidget;
export '/pages/parking/categories/categories_widget.dart' show CategoriesWidget;
export '/pages/parking/product_list_new_m/product_list_new_m_widget.dart'
    show ProductListNewMWidget;
export '/pages/parking/editproduct_new_m/editproduct_new_m_widget.dart'
    show EditproductNewMWidget;
export '/pages/parking/addproduct_a_p_p/addproduct_a_p_p_widget.dart'
    show AddproductAPPWidget;
export '/pages/parking/edit_category_m/edit_category_m_widget.dart'
    show EditCategoryMWidget;
export '/pages/parking/add_category_m/add_category_m_widget.dart'
    show AddCategoryMWidget;
export '/pages/parking/parking_check_i_n/parking_check_i_n_widget.dart'
    show ParkingCheckINWidget;
export '/pages/parking/parking_customers/parking_customers_widget.dart'
    show ParkingCustomersWidget;
export '/pages/parking/parking_product/parking_product_widget.dart'
    show ParkingProductWidget;
export '/pages/parking/edit_user_permission/edit_user_permission_widget.dart'
    show EditUserPermissionWidget;
export '/pages/parking/parking_product_copy/parking_product_copy_widget.dart'
    show ParkingProductCopyWidget;
export '/pages/parking/welcome_screen_parking/welcome_screen_parking_widget.dart'
    show WelcomeScreenParkingWidget;
export '/pages/parking/printersetting_car/printersetting_car_widget.dart'
    show PrintersettingCarWidget;
export '/pages/parking/subscription_new2/subscription_new2_widget.dart'
    show SubscriptionNew2Widget;
export '/pages/parking/deviceqr/deviceqr_widget.dart' show DeviceqrWidget;
export '/pages/parking/parking_report/parking_report_widget.dart'
    show ParkingReportWidget;
export '/pages/parking/number_plate_scanner/number_plate_scanner_widget.dart'
    show NumberPlateScannerWidget;
export '/pages/parking/billwisesalereport/billwisesalereport_widget.dart'
    show BillwisesalereportWidget;
export '/pages/parking/category_wise_sale_report/category_wise_sale_report_widget.dart'
    show CategoryWiseSaleReportWidget;
export '/pages/parking/product_wise_sale_report/product_wise_sale_report_widget.dart'
    show ProductWiseSaleReportWidget;
export '/pages/parking/day_wise_sale_report/day_wise_sale_report_widget.dart'
    show DayWiseSaleReportWidget;
export '/pages/parking/bill_details/bill_details_widget.dart'
    show BillDetailsWidget;
export '/pages/parking/dashboard/dashboard_widget.dart' show DashboardWidget;
export '/pages/parking/add_customer1/add_customer1_widget.dart'
    show AddCustomer1Widget;
export '/pages/parking/monthly_pass/monthly_pass_widget.dart'
    show MonthlyPassWidget;
export '/pages/parking/pass_details/pass_details_widget.dart'
    show PassDetailsWidget;
export '/pages/parking/vehicle_wise_sale_report/vehicle_wise_sale_report_widget.dart'
    show VehicleWiseSaleReportWidget;
export '/pages/parking/vehicle_entry/vehicle_entry_widget.dart'
    show VehicleEntryWidget;
export '/pages/parking/bill_entry/bill_entry_widget.dart' show BillEntryWidget;
export '/pages/parking/unbilled/unbilled_widget.dart' show UnbilledWidget;
export '/pages/parking/parking_report_new/parking_report_new_widget.dart'
    show ParkingReportNewWidget;
export '/pages/parking/vehicle_wise_sale2/vehicle_wise_sale2_widget.dart'
    show VehicleWiseSale2Widget;
export '/pages/parking/unbilled2/unbilled2_widget.dart' show Unbilled2Widget;
export '/pages/parking/in_out_report/in_out_report_widget.dart'
    show InOutReportWidget;
export '/pages/parking/todays_summary_report/todays_summary_report_widget.dart'
    show TodaysSummaryReportWidget;
export '/pages/dailly_collection_report/dailly_collection_report_widget.dart'
    show DaillyCollectionReportWidget;
export '/pages/parking/monthly_pass2/monthly_pass2_widget.dart'
    show MonthlyPass2Widget;
export '/web_parking/web_dashboard/web_dashboard_widget.dart'
    show WebDashboardWidget;
export '/web_parking/web_outlet_list_page/web_outlet_list_page_widget.dart'
    show WebOutletListPageWidget;
export '/web_parking/web_category_list/web_category_list_widget.dart'
    show WebCategoryListWidget;
export '/web_parking/web_add_category/web_add_category_widget.dart'
    show WebAddCategoryWidget;
export '/web_parking/web_edit_category/web_edit_category_widget.dart'
    show WebEditCategoryWidget;
export '/web_parking/web_vehicle_wise_sale_report/web_vehicle_wise_sale_report_widget.dart'
    show WebVehicleWiseSaleReportWidget;
export '/web_parking/web_in_out_report/web_in_out_report_widget.dart'
    show WebInOutReportWidget;
export '/web_parking/web_todays_summary_report/web_todays_summary_report_widget.dart'
    show WebTodaysSummaryReportWidget;
export '/web_parking/web_billwisesale_report/web_billwisesale_report_widget.dart'
    show WebBillwisesaleReportWidget;
export '/web_parking/web_daily_collection_report/web_daily_collection_report_widget.dart'
    show WebDailyCollectionReportWidget;
export '/web_parking/web_unbilled_receipts/web_unbilled_receipts_widget.dart'
    show WebUnbilledReceiptsWidget;
export '/web_parking/web_pass_details/web_pass_details_widget.dart'
    show WebPassDetailsWidget;
export '/web_parking/web_userwise_report/web_userwise_report_widget.dart'
    show WebUserwiseReportWidget;
export '/web_parking/web_product_list_new_m/web_product_list_new_m_widget.dart'
    show WebProductListNewMWidget;
export '/web_parking/web_addproduct_a_p_p/web_addproduct_a_p_p_widget.dart'
    show WebAddproductAPPWidget;
export '/web_parking/web_editproduct_new_m/web_editproduct_new_m_widget.dart'
    show WebEditproductNewMWidget;
export '/web_parking/web_login/web_login_widget.dart' show WebLoginWidget;
export '/pages/parking/user_account/user_account_widget.dart'
    show UserAccountWidget;
export '/pages/parking/add_user/add_user_widget.dart' show AddUserWidget;
export '/pages/parking/parking_login/parking_login_widget.dart'
    show ParkingLoginWidget;
export '/pages/parking/edit_outlet_page/edit_outlet_page_widget.dart'
    show EditOutletPageWidget;
export '/pages/parking/parking_check_i_n_copy/parking_check_i_n_copy_widget.dart'
    show ParkingCheckINCopyWidget;
export '/pages/parking/edit_bill_list/edit_bill_list_widget.dart'
    show EditBillListWidget;
export '/pages/parking/edit_bill_details/edit_bill_details_widget.dart'
    show EditBillDetailsWidget;
export '/web_parking/web_vehicle_wise_sale2/web_vehicle_wise_sale2_widget.dart'
    show WebVehicleWiseSale2Widget;
export '/pages/parking/app_settings/app_settings_widget.dart'
    show AppSettingsWidget;
export '/pages/parking/shift_end/shift_end_widget.dart' show ShiftEndWidget;
export '/pages/welcome_screen_new/welcome_screen_new_widget.dart'
    show WelcomeScreenNewWidget;
export '/pages/shift_summary_report/shift_summary_report_widget.dart'
    show ShiftSummaryReportWidget;
export '/pages/parking/shift_details/shift_details_widget.dart'
    show ShiftDetailsWidget;
export '/pages/parking/shift_wise_vehicle_report/shift_wise_vehicle_report_widget.dart'
    show ShiftWiseVehicleReportWidget;
export '/pages/parking/splash_parking/splash_parking_widget.dart'
    show SplashParkingWidget;
export '/web_parking/web_edit_userprofile/web_edit_userprofile_widget.dart'
    show WebEditUserprofileWidget;
export '/web_parking/web_user_account/web_user_account_widget.dart'
    show WebUserAccountWidget;
export '/web_parking/web_edit_user_permission/web_edit_user_permission_widget.dart'
    show WebEditUserPermissionWidget;
export '/web_parking/web_add_user/web_add_user_widget.dart'
    show WebAddUserWidget;
export '/web_parking/web_terminal_wise_report/web_terminal_wise_report_widget.dart'
    show WebTerminalWiseReportWidget;
export '/web_parking/web_user_details_report/web_user_details_report_widget.dart'
    show WebUserDetailsReportWidget;
